CREATE DATABASE IF NOT EXISTS game_db;
USE game_db;

CREATE TABLE IF NOT EXISTS snake_scores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    score INT NOT NULL,
    playtime DATETIME DEFAULT CURRENT_TIMESTAMP
);
